export enum Operation {
    EQUAL = "EQUAL",
    NOT_EQUAL = "NOT_EQUAL",
    LESS_THAN = "LESS_THAN",
    LESS_OR_EQUAL = "LESS_OR_EQUAL",
    GREATER_THAN = "GREATER_THAN",
    GREATER_OR_EQUAL = "GREATER_OR_EQUAL"
}
